#streamlit run app.py
# http://localhost:8501/
import streamlit as st
import requests
import plotly.express as px
import plotly.graph_objects as go
from fpdf import FPDF
import base64
import os

# 1. Force Wide Mode to occupy the whole space
st.set_page_config(page_title="AI Event Coordinator Pro", layout="wide")

# --- ADVANCED CSS: PASTEL THEME & HOVER EFFECTS ---
st.markdown("""
    <style>
    /* Occupy full width and light pastel background */
    .block-container {
        padding: 2rem 5rem;
        max-width: 100% !important;
    }
    .stApp { background-color: #f8f9fc; } /* Soft Pastel Slate */

    # /* Glassmorphism Card for Inputs */
    # .input-card {
    #     background: white;
    #     padding: 40px;
    #     border-radius: 25px;
    #     border: 1px solid #edf2f7;
    #     box-shadow: 0 10px 30px rgba(0,0,0,0.02);
    #     margin-bottom: 30px;
    #     text-align: center;
    #     text-shadow: 0 1px 3px rgba(0,0,0,0.1);
    #     text:
    # }

    /* Advanced Hover Button with Border */
    div.stButton > button:first-child {
        background-color: transparent;
        color: #5a67d8;
        border: 2px solid #5a67d8;
        border-radius: 15px;
        font-weight: 700;
        padding: 15px 30px;
        transition: all 0.4s ease-in-out;
        width: 100%;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    div.stButton > button:first-child:hover {
        background-color: #5a67d8;
        color: white;
        transform: translateY(-3px);
        box-shadow: 0 8px 20px rgba(90, 103, 216, 0.3);
    }
    </style>
    """, unsafe_allow_html=True)

st.title("🚀 AI Event Coordinator: Intelligent Orchestration 🚀 ", text_alignment="center")
st.markdown("Welcome to the AI Event Coordinator! This tool uses advanced AI to help you plan and execute your events seamlessly. Fill in the details below to get started.", text_alignment="center")
st.info("💡 Pro Tip: Use the 'Generate Complete Event Blueprint' button to see how all AI modules work together to create a comprehensive event plan.")

def save_pdf_to_disk(plan_data, target_path):
    # Ensure the Exports directory exists on your D: drive [cite: 61]
    if not os.path.exists(target_path):
        os.makedirs(target_path)
    
    pdf = FPDF()
    pdf.add_page()
    
    # Header Section
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(200, 15, txt="AI Event Coordinator: Event Blueprint", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt="Generated by Intelligent System for Automated Planning", ln=True, align='C')
    pdf.ln(10)
    
    # Map the modular tool outputs to PDF sections [cite: 30, 44]
    sections = {
        "Venue Recommendations": plan_data.get("venues", "No venue data found."),
        "Event Agenda": plan_data.get("agenda", "No agenda data found."),
        "Logistics and Resources": plan_data.get("logistics", "No logistics data found."),
        "Actionable Checklist": plan_data.get("checklist", "No checklist data found.")
    }
    
    for title, content in sections.items():
        # Section Header Styling
        pdf.set_font("Arial", 'B', 14)
        pdf.set_fill_color(240, 244, 248) 
        pdf.cell(0, 10, txt=title, ln=True, fill=True)
        
        # Section Content
        pdf.set_font("Arial", size=11)
        pdf.ln(2)
        
        # Clean special characters/emojis to prevent encoding errors
        clean_text = str(content).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 7, txt=clean_text)
        pdf.ln(5)
    
    # Define file name and full path
    file_name = f"Event_Plan_{plan_data['meta']['event_type'].replace(' ', '_')}.pdf"
    full_path = os.path.join(target_path, file_name)
    
    # Write file to disk
    pdf.output(full_path)
    return full_path
# --- INPUT SECTION (Requirement Collection Tool) ---
with st.container():
    st.markdown('<div class="input-card">', unsafe_allow_html=True)
    c1, c2, c3, c4 = st.columns([2, 1, 1, 2])
    
    with c1:
        event_type = st.selectbox("Event Category", ["Workshop", "Conference", "Corporate Meeting", "College Festival", "Birthday"])
    with c2:
        budget = st.number_input("Budget ($)", min_value=100, value=5000)
    with c3:
        attendee_count = st.number_input("Guest Count", min_value=1, value=100)
    with c4:
        location = st.text_input("Preferred Location", value="Mumbai")

    preferences = st.text_input("Special Preferences", "Modern, tech-focused, includes catering.")
    plan_button = st.button("Generate Complete Event Blueprint")
    st.markdown('</div>', unsafe_allow_html=True)

# --- BACKEND LOGIC ---

if plan_button:
    payload = {
        "event_type": event_type, 
        "budget": budget, 
        "location": location, 
        "attendee_count": attendee_count, 
        "duration_days": 1, 
        "preferences": preferences
    }
    BASE_URL = "http://127.0.0.1:8000"
    
    with st.spinner("AI Planning Engine Orchestrating..."):
        try:
            # Parallel calls to independent AI-assisted tools [cite: 12]
            v_res = requests.post(f"{BASE_URL}/recommend-venues/", json=payload).json()
            a_res = requests.post(f"{BASE_URL}/generate-agenda/", json=payload).json()
            b_res = requests.post(f"{BASE_URL}/plan-budget-logistics/", json=payload).json()
            c_res = requests.post(f"{BASE_URL}/generate-checklist/", json=payload).json()
            
            # Synchronizing keys for the PDF and UI modules [cite: 44]
            st.session_state.event_plan = {
                "venues": v_res.get("recommendations"),
                "agenda": a_res.get("agenda"),
                "budget_breakdown": b_res.get("budget_breakdown"),
                "logistics": b_res.get("logistics_recommendations"), # Key fixed here
                "checklist": c_res.get("checklist"),
                "meta": payload # Critical for Tab 6 and PDF headers
            }
            st.success("Blueprint ready!")
            st.session_state.plan = {"venues": v_res, "agenda": a_res, "budget": b_res, "checklist": c_res}


        except Exception as e:
            st.error(f"Connection failed: {e}. Ensure FastAPI is running.")

# --- NAVIGATION TABS (Occupying Whole Space) ---
if "plan" in st.session_state:
    p = st.session_state.plan
    tabs = st.tabs(["📍 Venues", "📅 Agenda", "💳 Budgeting", "🛠️ Resources", "✅ Checklist", "📊 Data View", "📥 Export"])

    with tabs[0]:
        st.subheader("Venue Recommendation Tool")
        st.info(p["venues"].get("recommendations"))
    with tabs[1]:
        # st.subheader("Schedule & Agenda Generator")
        # # Mock data for visualization based on AI output
        # df = [dict(Task="Registration", Start='09:00', Finish='10:00'),
        #     dict(Task="Keynote", Start='10:00', Finish='11:30')]
        # fig = px.timeline(df, x_start="Start", x_end="Finish", y="Task", color_discrete_sequence=['#63b3ed'])
        # st.plotly_chart(fig, use_container_width=True)
        # st.write(p["agenda"].get("agenda"))
        st.subheader("Schedule & Agenda Generator")
        st.write(p["agenda"].get("agenda"))

    with tabs[2]:
        st.subheader("Budget Planning Tool")
        breakdown = p["budget"].get("budget_breakdown")

    with tabs[3]:
        st.subheader("Resource & Logistics Management")
        st.write(p["budget"].get("logistics_recommendations"))

    with tabs[4]:
        st.subheader("Checklist & Task Automation")
        st.markdown(p["checklist"].get("checklist"))

    with tabs[5]:
        st.subheader("Structured Output (JSON)")
        st.json(p)

    with tabs[6]: 
        st.subheader("📥 Export Final Blueprint")
        st.markdown("---")
        
        # Path on your D: drive as requested
        export_dir = r"D:\Internship\Projects\ai-event-coordinator(Proj2)\Exports"
        
        # FIX: Only attempt to access event_plan if it exists
        if "event_plan" in st.session_state:
            st.write("Click below to finalize your event plan and save it to your local disk.")

            if st.button("Generate and Save PDF", use_container_width=True):
                # Safe to access now because we confirmed it exists above
                p = st.session_state.event_plan
                
                try:
                    with st.spinner("Writing blueprint to Exports folder..."):
                        final_path = save_pdf_to_disk(p, export_dir)
                    
                    st.success(f"Success! File saved to: {final_path}")
                    st.info("The PDF is now ready for your final project submission walkthrough.")
                    
                except Exception as e:
                    st.error(f"Failed to export PDF: {e}")
        else:
            # Message shown before the user generates a plan
            st.warning("Please configure your event and click 'Generate Event Blueprint' first to enable export.")